export default class OperatorType {
    OPERATOR_START_GAME = 1
    OPERATOR_SKIP = 2
    OPERATOR_DRAW = 3
    OPERATOR_DAHAI = 4
    OPERATOR_RON = 5
    OPERATOR_PON = 6
    OPERATOR_CHI = 7
    OPERATOR_DAIMINKAN = 8
    OPERATOR_TSUMO = 9
    OPERATOR_ANKAN = 10
    OPERATOR_KAKAN = 11
    OPERATOR_PE = 12
    OPERATOR_KYUSHUKYUHAI = 13
    OPERATOR_REACH = 14
    OPERATOR_OK = 15
}

